In [1]:
import numpy as np
import networkx as nx
from karateclub import NetMF
import torch
from torch_geometric.data import Data

In [2]:
fc_matrices=np.load('../source_data/fc/fc_matrices.npy')

In [3]:
connectivity_matrix=fc_matrices[0]

In [4]:
threshold=0.5
adjacency_matrix = (connectivity_matrix > threshold).astype(float)
graph = nx.from_numpy_matrix(adjacency_matrix)

In [5]:
# NetMF embedding logic using karate club module
def netmf_embedding(graph, dimensions=16, order=2):
    model = NetMF(dimensions=dimensions, order=order,seed=21)
    model.fit(graph)
    return model.get_embedding()

In [6]:
netmf_embeddings = netmf_embedding(graph, dimensions=32, order=2)


In [7]:
print(netmf_embeddings.shape)

(39, 32)


In [8]:
# Extract node features from the embeddings
node_features = torch.tensor(netmf_embeddings, dtype=torch.float32)

In [10]:
node_features

tensor([[ 3.7035e-02,  3.2525e-01,  4.8248e-01,  ...,  3.3613e-03,
          7.1995e-03,  2.9877e-03],
        [ 4.2926e-02,  1.5945e-01,  4.0567e-01,  ...,  4.5217e-03,
          5.8696e-03, -2.8741e-04],
        [ 3.4563e-02,  2.6487e-01,  8.2015e-02,  ...,  3.0255e-03,
         -2.1931e-04, -2.0832e-04],
        ...,
        [ 1.5258e-03,  1.6080e-02,  5.3199e-03,  ...,  1.1198e-02,
         -1.4195e-04, -4.4505e-03],
        [ 1.8902e-02,  2.8268e-01,  4.6883e-01,  ..., -2.3394e-03,
         -5.1105e-03, -2.1431e-03],
        [ 9.5227e-02,  8.6666e-02,  6.8740e-01,  ...,  1.0335e-04,
          1.4637e-03, -2.2891e-03]])

In [9]:
adjacency_matrix

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [12]:
edge_index = torch.tensor(adjacency_matrix.nonzero(), dtype=torch.long)

In [13]:
edge_index

tensor([[ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
          2,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  8,  8,  8,
          8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
         14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18,
         18, 18, 19, 19, 19, 19, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22,
         22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24,
         24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
         26, 26, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29,
         29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32,
         32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 36, 36, 37,
         38, 38, 38, 38],
  

In [14]:
edge_index = torch.tensor(np.array(np.where(adjacency_matrix != 0)), dtype=torch.long)

In [15]:
edge_index

tensor([[ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
          2,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  8,  8,  8,
          8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
         14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18,
         18, 18, 19, 19, 19, 19, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22,
         22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24,
         24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
         26, 26, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29,
         29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32,
         32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 36, 36, 37,
         38, 38, 38, 38],
  

In [48]:
data = Data(x=node_features, edge_index=edge_index)

In [49]:
print(data)

Data(x=[39, 32], edge_index=[2, 149])


In [ ]:
# Extract edge indices from the adjacency_matrix
edge_indices = torch.tensor(np.transpose(np.nonzero(adjacency_matrix)), dtype=torch.long)

# Create PyTorch Geometric Data object
data = Data(x=node_features, edge_index=edge_indices.t().contiguous(), y=torch.tensor(labels))