In [1]:
import numpy as np
import networkx as nx
from karateclub import NetMF
import torch
from torch_geometric.data import Data

In [2]:
fc_matrices=np.load('../source_data/fc/fc_matrices.npy')

In [3]:
connectivity_matrix=fc_matrices[0]

In [4]:
threshold=0.5
adjacency_matrix = (connectivity_matrix > threshold).astype(float)
graph = nx.from_numpy_matrix(adjacency_matrix)

In [5]:
# NetMF embedding logic using karate club module
def netmf_embedding(graph, dimensions=16, order=2):
    model = NetMF(dimensions=dimensions, order=order,seed=21)
    model.fit(graph)
    return model.get_embedding()

In [6]:
netmf_embeddings = netmf_embedding(graph, dimensions=32, order=2)


In [20]:
netmf_embeddings

array([[ 3.70348059e-02,  3.25251758e-01,  4.82475817e-01, ...,
         3.36130708e-03,  7.19951093e-03,  2.98769772e-03],
       [ 4.29261923e-02,  1.59452245e-01,  4.05669242e-01, ...,
         4.52171545e-03,  5.86961396e-03, -2.87413597e-04],
       [ 3.45632210e-02,  2.64867753e-01,  8.20153505e-02, ...,
         3.02554481e-03, -2.19310343e-04, -2.08318233e-04],
       ...,
       [ 1.52577541e-03,  1.60797779e-02,  5.31985285e-03, ...,
         1.11983716e-02, -1.41948927e-04, -4.45048511e-03],
       [ 1.89018399e-02,  2.82678068e-01,  4.68829989e-01, ...,
        -2.33941898e-03, -5.11053205e-03, -2.14309990e-03],
       [ 9.52267870e-02,  8.66663456e-02,  6.87404931e-01, ...,
         1.03347935e-04,  1.46367773e-03, -2.28907168e-03]], dtype=float32)

In [7]:
print(netmf_embeddings.shape)

(39, 32)


In [8]:
# Extract node features from the embeddings
node_features = torch.tensor(netmf_embeddings, dtype=torch.float32)

In [19]:
node_features.shape

torch.Size([39, 32])

In [10]:
adjacency_matrix

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [13]:
edge_index = torch.tensor(np.array(adjacency_matrix.nonzero()), dtype=torch.long)

In [14]:
edge_index

tensor([[ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
          2,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  8,  8,  8,
          8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
         14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18,
         18, 18, 19, 19, 19, 19, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22,
         22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24,
         24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
         26, 26, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29,
         29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32,
         32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 36, 36, 37,
         38, 38, 38, 38],
  

In [15]:
edge_index = torch.tensor(np.array(np.where(adjacency_matrix != 0)), dtype=torch.long)

In [16]:
edge_index

tensor([[ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
          2,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  8,  8,  8,
          8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
         14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18,
         18, 18, 19, 19, 19, 19, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22,
         22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24,
         24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
         26, 26, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29,
         29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32,
         32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 36, 36, 37,
         38, 38, 38, 38],
  

In [17]:
data = Data(x=node_features, edge_index=edge_index)

In [18]:
print(data)

Data(x=[39, 32], edge_index=[2, 220])
